openapi: 3.0.3
info:
  title: Scheduler Client API
  version: 1.0.0

paths:
  /events-reader:
    get:
      tags:
        - ReaderService
      operationId: getEvents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserEvent'

  /events-writer:
    post:
      tags:
        - WriterService
      operationId: writeEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserEvent'
      responses:
        '201':
          description: Created

components:
  schemas:
    UserEvent:
      type: object
      properties:
        eventType:
          type: string
        eventTime:
          type: string
          format: date-time
      required:
        - eventType
        - eventTime
